services:
  mongo:
    image: mongo:7.0.5
    container_name: bezkoder_DB
    ports:
      - 27017:27017
    restart: on-failure:3
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_USER_DB}
      MONGO_USER_DB: ${MONGO_USER_DB}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - services

networks:
  services:


